'use strict';
const left=document.querySelector('#baseline-video'),right=document.querySelector('#ours-video');
const videos=[left,right],seek=document.querySelector('#pair-seek'),play=document.querySelector('#play-pair'),status=document.querySelector('.player-status');
let mode='ar_refiner',scene=0,busy=false,playing=false,version=0;
const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function pause(){playing=false;videos.forEach(v=>v.pause());play.textContent='Play both';}
function ready(v){if(v.readyState>=1)return Promise.resolve();return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>done(new Error('Loading took too long. Press play to retry.')),20000);const ok=()=>done(),fail=()=>done(new Error('Unable to load video. Please retry.'));function done(err){clearTimeout(timeout);v.removeEventListener('loadedmetadata',ok);v.removeEventListener('error',fail);err?reject(err):resolve();}v.addEventListener('loadedmetadata',ok);v.addEventListener('error',fail);});}
async function start(){const request=version;status.textContent='';busy=true;try{await Promise.all(videos.map(ready));if(request!==version)return;right.currentTime=left.currentTime;await Promise.all(videos.map(v=>v.play()));if(request!==version){pause();return;}playing=true;play.textContent='Pause both';}catch(e){pause();status.textContent=e.message;}finally{busy=false;}}
async function jump(time){pause();const request=version;try{await Promise.all(videos.map(ready));if(request!==version)return;videos.forEach(v=>v.currentTime=Math.min(time,v.duration-.08));seek.value=time;}catch(e){status.textContent=e.message;}}
function choose(i){version++;pause();scene=i;const s=SAMPLES.filter(s=>s.group===mode)[scene];status.textContent='';videos.forEach((v,j)=>{const m=s.methods[j?'ours':'baseline'];v.poster=m.poster;v.src=m.video;v.load();});document.querySelectorAll('.sample-picks button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));document.querySelector('#sample-caption').textContent=`${s.title} · ${s.split}-Trajectory · ${s.inference_mode || s.mode} · Full sequence · 16 FPS`;seek.value=0;}
function changeMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));const picks=document.querySelector('.sample-picks');picks.replaceChildren();SAMPLES.filter(s=>s.group===mode).forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<img src="${s.methods.ours.poster}" alt="" loading="lazy"><span>${s.title}</span>`;b.setAttribute('aria-label',`Watch ${s.title}`);b.addEventListener('click',()=>choose(i));picks.append(b);});choose(scene);}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>changeMode(b.dataset.mode)));
play.addEventListener('click',()=>playing?pause():start());document.querySelector('#restart-pair').addEventListener('click',()=>jump(0));seek.addEventListener('input',()=>jump(Number(seek.value)));
videos.forEach((v,i)=>{v.addEventListener('play',()=>{if(!busy&&!playing){if(i)left.currentTime=right.currentTime;start();}});v.addEventListener('pause',()=>{if(!busy&&playing)pause();});v.addEventListener('ended',pause);v.addEventListener('seeking',()=>{const other=videos[1-i];if(Math.abs(other.currentTime-v.currentTime)>.15)other.currentTime=v.currentTime;});v.addEventListener('error',()=>{status.textContent='This video could not load. Select the scene again to retry.';});});
left.addEventListener('timeupdate',()=>{seek.max=Number.isFinite(left.duration)?left.duration-.08:60;seek.value=left.currentTime;document.querySelector('.clock').textContent=`${fmt(left.currentTime)} / ${fmt(left.duration||60)}`;if(playing&&!left.seeking&&!right.seeking&&Math.abs(left.currentTime-right.currentTime)>.25)right.currentTime=left.currentTime;});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)pause();}),{threshold:.05}).observe(document.querySelector('#videos'));
changeMode(mode);
